#ifndef FUSED_LI_MANAGE_MTP_TEMPLATE_TILING_KEY_H_
#define FUSED_LI_MANAGE_MTP_TEMPLATE_TILING_KEY_H_
#include "ascendc/host_api/tiling/template_argument.h"
#define LI_MTP_TPL_FP16 1
#define LI_MTP_TPL_BF16 27
ASCENDC_TPL_ARGS_DECL(NanovllmFusedLiManageMtp,
                      ASCENDC_TPL_DTYPE_DECL(DT, LI_MTP_TPL_FP16, LI_MTP_TPL_BF16));
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DTYPE_SEL(DT, LI_MTP_TPL_FP16)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DTYPE_SEL(DT, LI_MTP_TPL_BF16)), );
#endif
